name: Auto Generate

on:
  workflow_dispatch:
  push:
    branches: auto-generate

jobs:
  data:
    name: Get Version Data
    runs-on: ubuntu-latest
    outputs:
      release_changed: ${{steps.get-manifest.outputs.version-release-changed}}
      release_version: ${{steps.get-manifest.outputs.version-current-release}}
      release_url: ${{steps.get-manifest.outputs.version-current-release-url}}
      snapshot_changed: ${{steps.get-manifest.outputs.version-release-changed}}
      snapshot_version: ${{steps.get-manifest.outputs.version-current-snapshot}}
      snapshot_url: ${{steps.get-manifest.outputs.version-current-snapshot-url}}
    permissions:
      contents: write
      actions: read
      checks: write
    steps:
      - name: Get Manifest Data
        id: get-manifest
        uses: Datapack-Registry/minecraft-manifest@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build_release:
    name: Release
    needs: data
    if: ${{ needs.data.outputs.release_changed == 'true' || always() }}
    uses: ./.github/workflows/build_pack.yml
    with:
      is_full_release: true
      version_name: ${{ needs.data.outputs.release_version }}
      version_url: ${{ needs.data.outputs.release_url }}

  build_snapshot:
    name: Snapshot
    needs: data
    if: ${{ needs.data.outputs.snapshot_changed == 'true' || always() }}
    uses: ./.github/workflows/build_pack.yml
    with:
      is_full_release: false
      version_name: ${{ needs.data.outputs.snapshot_version }}
      version_url: ${{ needs.data.outputs.snapshot_url }}
