name: Auto Generate

on:
  workflow_dispatch:
  push:
    branches: auto-generate

env:
  version_manifest: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      versions: ${{steps.data.outputs.versions}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: resource-pack
      - name: Get data
        id: data
        run: |
          wget -O all_versions.json ${{env.version_manifest}}
          jq --compact-output '.latest as {snapshot: $snap, release: $real} | [ (.versions[] | select(.id == $real)), (.versions[] | select(.id == $snap)) ] | map({current: "", new: .id, url})' all_versions.json > versions.json

          printf '%s%s' "versions=" $(cat versions.json) >> $GITHUB_OUTPUT

  check_version:
    name: Check Version
    needs: generate
    strategy:
      matrix:
        release_type: [release, snapshot]
    uses: ./.github/workflows/check_version.yml
    with:
      is_full_release: ${{ matrix.release_type == 'release' }}
      current_version: ${{ fromJSON(needs.generate.outputs.versions)[matrix.release_type != 'release'].current }}
      new_version: ${{ fromJSON(needs.generate.outputs.versions)[matrix.release_type != 'release'].new }}
      version_url: ${{ fromJSON(needs.generate.outputs.versions)[matrix.release_type != 'release'].url }}
