name: Auto Generate

on:
  workflow_dispatch:
  push:
    branches: auto-generate

env:
  version_manifest: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json

jobs:
  data:
    name: Get Version Data
    runs-on: ubuntu-latest
    outputs:
      release_changed: ${{steps.get-manifest.outputs.version-release-changed}}
      release_version: ${{steps.get-manifest.outputs.version-current-release}}
      release_url: ${{steps.get-url.outputs.version-release-url}}
      snapshot_changed: ${{steps.get-manifest.outputs.version-release-changed}}
      snapshot_version: ${{steps.get-manifest.outputs.version-current-snapshot}}
      snapshot_url: ${{steps.get-url.outputs.version-snapshot-url}}
    permissions:
      contents: write
      actions: read
      checks: write
    steps:
      - name: Get Manifest Data
        id: get-manifest
        uses: Datapack-Registry/minecraft-manifest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Temp: Get Version URL'
        id: get-url
        run: |
          wget -O all_versions.json ${{env.version_manifest}}
          printf "version-release-url=%s" $(jq --compact-output '.versions[] | select(.id == ${{ steps.get-manifest.outputs.version-current-release }}).url' versions.json) >> $GITHUB_OUTPUT
          printf "version-snapshot-url=%s" $(jq --compact-output '.versions[] | select(.id == ${{ steps.get-manifest.outputs.version-current-snapshot }}).url' versions.json) >> $GITHUB_OUTPUT

  build_release:
    name: Build Release Pack
    needs: data
    if: ${{ needs.data.outputs.release_changed }}
    uses: ./.github/workflows/build_pack.yml
    with:
      is_full_release: true
      version_name: ${{ needs.data.outputs.release_version }}
      version_url: ${{ needs.data.outputs.release_url }}

  build_snapshot:
    name: Build Snapshot Pack
    needs: data
    if: ${{ needs.data.outputs.snapshot_changed }}
    uses: ./.github/workflows/build_pack.yml
    with:
      is_full_release: false
      version_name: ${{ needs.data.outputs.snapshot_version }}
      version_url: ${{ needs.data.outputs.snapshot_url }}
