name: Check version

on:
  workflow_call:
    inputs:
      is_full_release:
        description: Type of the release, true for a full release or false for a snapshot
        required: true
        type: boolean
      current_version:
        description: The name of the Minecraft version currently beeing used
        required: true
        type: string
      new_version:
        description: The name of the new Minecraft version to compare to the current one
        required: true
        type: string
      version_url:
        description: The download url for the Minecraft version json file to build the pack from
        required: true
        type: string

jobs:
  check:
    name: Check version
    if: ${{ inputs.current_version != inputs.new_version }}
    uses: ./.github/workflows/build_pack.yml
    with:
      version_name: ${{ inputs.new_version }}
      version_url: ${{ inputs.version_url }}
      is_full_release: ${{ inputs.is_full_release }}
